name: 'Zola Deploy to Pages'
description: 'Build and deploy a Zola site to GitHub Pages with chineses support'
author: 'Shaleen Jain and littleji'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'zap'  
  color: 'green'
